language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t rahulvdalal/docker-react .

script:
  - docker run -e CI=true rahulvdalal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-609756519390"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

